version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: RecommenderSystemDB

  web:
    image: aniagud/recommender_system:v2
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8000