version: '3.1'

services:

  db:
    build: ./db/
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: RecommenderSystemDB
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    image: aniagud/recommender_system:v2
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  postgres-data: